### ISSUE TITLE
 Cannot read property 'getSignature' of undefined

### ISSUE THREAD

**Issue by ryanchanplc** [jyfcrw/botbuilder-wechat-connector#1]
Hi ,

i got this error when the server receiving messages using the tests/example.js.  Please help. 

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'getSignature' of undefined
    at /home/ubuntu/wechat/ms/bot/node_modules/botbuilder-wechat-connector/node_modules/wechat/lib/wechat.js:450:34
    at Parser.<anonymous> (/home/ubuntu/wechat/ms/bot/node_modules/botbuilder-wechat-connector/node_modules/xml2js/lib/xml2js.js:483:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Object.onclosetag (/home/ubuntu/wechat/ms/bot/node_modules/botbuilder-wechat-connector/node_modules/xml2js/lib/xml2js.js:444:26)
    at emit (/home/ubuntu/wechat/ms/bot/node_modules/botbuilder-wechat-connector/node_modules/sax/lib/sax.js:640:35)
    at emitNode (/home/ubuntu/wechat/ms/bot/node_modules/botbuilder-wechat-connector/node_modules/sax/lib/sax.js:645:5)
    at closeTag (/home/ubuntu/wechat/ms/bot/node_modules/botbuilder-wechat-connector/node_modules/sax/lib/sax.js:905:7)
    at Object.write (/home/ubuntu/wechat/ms/bot/node_modules/botbuilder-wechat-connector/node_modules/sax/lib/sax.js:1449:13)
    at Parser.exports.Parser.Parser.parseString (/home/ubuntu/wechat/ms/bot/node_modules/botbuilder-wechat-connector/node_modules/xml2js/lib/xml2js.js:502:31)
```

**Comment by ryanchanplc** [comment]
finally i have found the solution . 

encodingAESKey is need to included in the connectors config.

```
var wechatConnector = new connector.WechatConnector({
    appID: "YOUR WECHAT APP ID",
    appSecret: "YOUR WECHAT APP SECRET",
    appToken: "YOUR WECHAT TOKEN",
    encodingAESKey:"YOUR AES KEY"
});
```

**Comment by ryanchanplc** [comment]
the reason is that my wechat account is not yet certified by wechat

**Comment by jyfcrw** [comment]
Hi, @ryanchanplc , sorry for not replying in time. 
Yes, wechat official account must be certified, or try registering a trial official account from [this link](http://mp.weixin.qq.com/debug/cgi-bin/sandbox?t=sandbox/login) for developing or debugging.
